import logging

from openai import (
    APIError,
    AuthenticationError,
    RateLimitError
)

from app.ai.llm_client import LlmClient
from app.ai.prompt_builder import PromptBuilder


logger = logging.getLogger(__name__)


class ExplanationService:

    def __init__(self):

        self.prompt_builder = PromptBuilder()

        self.llm_client = LlmClient()

    def explain(self, build):

        prompt = self.prompt_builder.build_prompt(build)

        try:

            return self.llm_client.generate(prompt)

        except RateLimitError as ex:

            logger.error(
                "OpenAI rate limit/quota exceeded.",
                exc_info=ex
            )

            return (
                "AI explanation is temporarily unavailable because "
                "the language model quota has been reached."
            )

        except AuthenticationError as ex:

            logger.error(
                "OpenAI authentication failed.",
                exc_info=ex
            )

            return (
                "AI explanation is unavailable due to an "
                "authentication issue."
            )

        except APIError as ex:

            logger.error(
                "OpenAI API error.",
                exc_info=ex
            )

            return (
                "AI explanation service is temporarily unavailable."
            )

        except Exception as ex:

            logger.exception(
                "Unexpected error while generating AI explanation."
            )

            return (
                "AI explanation is temporarily unavailable. "
                "The recommended build is still valid because it "
                "was generated by the recommendation engine."
            )
