"""create component aliases table

Revision ID: 3449611c7b9e
Revises: a0f633ceef1f
Create Date: 2026-06-13 18:29:08.353510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3449611c7b9e'
down_revision: Union[str, Sequence[str], None] = 'a0f633ceef1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_aliases')
    # ### end Alembic commands ###
