"""add unique constraint to component name

Revision ID: c5358b087eff
Revises: d940f3765135
Create Date: 2026-06-14 16:25:16.046872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5358b087eff'
down_revision: Union[str, Sequence[str], None] = 'd940f3765135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'components', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'components', type_='unique')
    # ### end Alembic commands ###
