"""create recommendation rules table

Revision ID: d940f3765135
Revises: e811e6fc847c
Create Date: 2026-06-13 19:07:49.377251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd940f3765135'
down_revision: Union[str, Sequence[str], None] = 'e811e6fc847c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_component_type', sa.String(length=50), nullable=False),
    sa.Column('source_tier', sa.Integer(), nullable=False),
    sa.Column('target_component_type', sa.String(length=50), nullable=False),
    sa.Column('min_target_tier', sa.Integer(), nullable=False),
    sa.Column('max_target_tier', sa.Integer(), nullable=False),
    sa.Column('build_profile', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_rules')
    # ### end Alembic commands ###
